# Generated by Django 5.2.4 on 2025-07-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0003_menuitem_registereduser_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
