# Generated by Django 5.2.4 on 2025-10-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0004_remove_menuitem_name_remove_registereduser_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='journal_covers/')),
            ],
        ),
    ]
