# Generated by Django 5.2.4 on 2025-11-18 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0005_journal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=100)),
                ('from_location', models.CharField(blank=True, max_length=255)),
                ('to_location', models.CharField(blank=True, max_length=255)),
                ('depart_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('cabin', models.CharField(default='Economy', max_length=50)),
                ('budget', models.PositiveIntegerField()),
                ('accommodation', models.CharField(max_length=50)),
                ('trip_type', models.CharField(blank=True, max_length=50)),
                ('special_requests', models.TextField(blank=True)),
                ('pref_direct', models.BooleanField(default=False)),
                ('pref_window', models.BooleanField(default=False)),
                ('pref_breakfast', models.BooleanField(default=False)),
                ('pref_attractions', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='menu_items',
        ),
        migrations.DeleteModel(
            name='RegisteredUser',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
